name: testing the asciidoc convert action

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build âš™
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: .
        with:
          slides: true
          inputPath: input
          outputPath: output
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ github.TOKEN }}
          BRANCH: gh-pages
          FOLDER: output
